alter table if exists public.products enable row level security;
alter table if exists public.bundles enable row level security;
alter table if exists public.blog_posts enable row level security;
alter table if exists public.media enable row level security;
alter table if exists public.settings enable row level security;
alter table if exists public.orders enable row level security;
alter table if exists public.services enable row level security;
alter table if exists public.courses enable row level security;
alter table if exists public.course_modules enable row level security;
alter table if exists public.course_lessons enable row level security;
alter table if exists public.course_enrollments enable row level security;
alter table if exists public.projects enable row level security;
alter table if exists public.leads enable row level security;

create table public.products (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now() not null,
  title text not null,
  slug text not null unique,
  description text,
  price numeric not null,
  cover_image text,
  active boolean default true not null,
  sort_order integer default 0 not null
);

create table public.bundles (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now() not null,
  name text not null,
  slug text not null unique,
  description text,
  price numeric not null,
  cover_image text,
  active boolean default true not null,
  sort_order integer default 0 not null
);

create table public.blog_posts (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now() not null,
  title text not null,
  slug text not null unique,
  content text not null,
  excerpt text,
  published_at timestamp with time zone,
  active boolean default true not null
);

create table public.media (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now() not null,
  path text not null,
  url text not null,
  type text not null,
  size bigint,
  used_in jsonb
);

create table public.settings (
  key text primary key,
  value text not null,
  updated_at timestamp with time zone default now() not null
);

create table public.orders (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now() not null,
  customer_email text,
  items jsonb not null,
  total numeric not null,
  payment_status text default 'pending' not null
);

-- Create services table
-- Central admin gate: an account is an admin only when its metadata role is
-- 'admin' AND it has an approved row in admin_approvals (service-role managed).
create table if not exists public.admin_approvals (
  user_id uuid primary key references auth.users(id) on delete cascade,
  approved boolean not null default false,
  requested_at timestamptz default now() not null,
  decided_at timestamptz,
  decided_by uuid references auth.users(id)
);
alter table if exists public.admin_approvals enable row level security;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.admin_approvals aa
    join auth.users u on u.id = aa.user_id
    where aa.user_id = auth.uid()
      and aa.approved = true
      and u.raw_user_meta_data->>'role' = 'admin'
  );
$$;

CREATE TABLE IF NOT EXISTS public.services (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  title TEXT NOT NULL,
  SLUG TEXT NOT NULL UNIQUE,
  short_description TEXT,
  full_content TEXT,
  icon TEXT,
  features JSONB DEFAULT '[]'::jsonb,
  pricing_info JSONB,
  active BOOLEAN DEFAULT TRUE NOT NULL,
  featured BOOLEAN DEFAULT FALSE NOT NULL,
  sort_order INTEGER DEFAULT 0 NOT NULL,
  seo_title TEXT,
  seo_description TEXT
);

-- Enable Row Level Security
ALTER TABLE IF EXISTS public.services ENABLE ROW LEVEL SECURITY;

-- Create policies for services
CREATE POLICY "Services are viewable by everyone" ON public.services
  FOR SELECT USING (active = TRUE);

CREATE POLICY "Services are manageable by admins" ON public.services
  FOR ALL USING (auth.role() = 'service_role' OR public.is_admin());

-- Create courses table
CREATE TABLE IF NOT EXISTS public.courses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  title TEXT NOT NULL,
  SLUG TEXT NOT NULL UNIQUE,
  short_description TEXT,
  full_description TEXT,
  instructor TEXT,
  thumbnail TEXT,
  banner TEXT,
  regular_price NUMERIC,
  discounted_price NUMERIC,
  difficulty_level TEXT CHECK (difficulty_level IN ('beginner', 'intermediate', 'advanced')),
  duration TEXT,
  num_lessons INTEGER DEFAULT 0,
  features JSONB DEFAULT '[]'::jsonb,
  requirements JSONB DEFAULT '[]'::jsonb,
  what_youll_learn JSONB DEFAULT '[]'::jsonb,
  featured BOOLEAN DEFAULT FALSE NOT NULL,
  popular BOOLEAN DEFAULT FALSE NOT NULL,
  new_course BOOLEAN DEFAULT FALSE NOT NULL,
  published BOOLEAN DEFAULT FALSE NOT NULL,
  enrollment_status TEXT DEFAULT 'closed' CHECK (enrollment_status IN ('open', 'closed', 'coming_soon')),
  seo_title TEXT,
  seo_description TEXT
);

-- Enable Row Level Security
ALTER TABLE IF EXISTS public.courses ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.course_modules ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.course_lessons ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.course_enrollments ENABLE ROW LEVEL SECURITY;

-- Create policies for courses
CREATE POLICY "Published courses are viewable by everyone" ON public.courses
  FOR SELECT USING (published = TRUE);

CREATE POLICY "Courses are manageable by admins" ON public.courses
  FOR ALL USING (auth.role() = 'service_role' OR public.is_admin());

-- Similar policies for modules and lessons
CREATE POLICY "Modules are viewable by everyone" ON public.course_modules
  FOR SELECT USING (TRUE);

CREATE POLICY "Modules are manageable by admins" ON public.course_modules
  FOR ALL USING (auth.role() = 'service_role' OR public.is_admin());

CREATE POLICY "Lessons are viewable by everyone" ON public.course_lessons
  FOR SELECT USING (is_preview = TRUE OR EXISTS (
    SELECT 1 FROM public.course_enrollments ce
    JOIN public.course_modules cm ON ce.module_id = cm.id
    WHERE ce.user_id = auth.uid() AND ce.status = 'active'
  ));

CREATE POLICY "Lessons are manageable by admins" ON public.course_lessons
  FOR ALL USING (auth.role() = 'service_role' OR public.is_admin());

-- Policies for enrollments
CREATE POLICY "Users can view their own enrollments" ON public.course_enrollments
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own enrollments" ON public.course_enrollments
  FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Enrollments are manageable by admins" ON public.course_enrollments
  FOR ALL USING (auth.role() = 'service_role' OR public.is_admin());

-- Create projects table
CREATE TABLE IF NOT EXISTS public.projects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  title TEXT NOT NULL,
  SLUG TEXT NOT NULL UNIQUE,
  client_business TEXT,
  category TEXT,
  technologies JSONB DEFAULT '[]'::jsonb,
  description TEXT,
  problem TEXT,
  solution TEXT,
  screenshots JSONB DEFAULT '[]'::jsonb,
  website_url TEXT,
  app_urls JSONB DEFAULT '[]'::jsonb,
  featured BOOLEAN DEFAULT FALSE NOT NULL,
  completion_date DATE,
  seo_title TEXT,
  seo_description TEXT
);

-- Enable Row Level Security
ALTER TABLE IF EXISTS public.projects ENABLE ROW LEVEL SECURITY;

-- Create policies for projects
CREATE POLICY "Projects are viewable by everyone" ON public.projects
  FOR SELECT USING (TRUE);

CREATE POLICY "Projects are manageable by admins" ON public.projects
  FOR ALL USING (auth.role() = 'service_role' OR public.is_admin());

-- Create leads table
CREATE TABLE IF NOT EXISTS public.leads (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT,
  company TEXT,
  project_type TEXT,
  budget_range TEXT,
  required_service TEXT,
  project_description TEXT,
  preferred_contact_method TEXT,
  status TEXT DEFAULT 'new' CHECK (status IN ('new', 'contacted', 'qualified', 'in_progress', 'won', 'lost')),
  internal_notes TEXT
);

-- Enable Row Level Security
ALTER TABLE IF EXISTS public.leads ENABLE ROW LEVEL SECURITY;

-- Create policies for leads
CREATE POLICY "Leads are insertable by everyone" ON public.leads
  FOR INSERT WITH CHECK (TRUE);

CREATE POLICY "Leads are manageable by admins" ON public.leads
  FOR ALL USING (auth.role() = 'service_role' OR public.is_admin());

-- Policies for products
CREATE POLICY "Products are viewable by everyone" ON public.products
  FOR SELECT USING (active = TRUE);

CREATE POLICY "Products are manageable by admins" ON public.products
  FOR ALL USING (auth.role() = 'service_role' OR public.is_admin());

-- Policies for bundles
CREATE POLICY "Bundles are viewable by everyone" ON public.bundles
  FOR SELECT USING (active = TRUE);

CREATE POLICY "Bundles are manageable by admins" ON public.bundles
  FOR ALL USING (auth.role() = 'service_role' OR public.is_admin());

-- Policies for blog_posts
CREATE POLICY "Blog posts are viewable by everyone" ON public.blog_posts
  FOR SELECT USING (active = TRUE);

CREATE POLICY "Blog posts are manageable by admins" ON public.blog_posts
  FOR ALL USING (auth.role() = 'service_role' OR public.is_admin());

-- Policies for media
CREATE POLICY "Media is viewable by everyone" ON public.media
  FOR SELECT USING (TRUE);

CREATE POLICY "Media is manageable by admins" ON public.media
  FOR ALL USING (auth.role() = 'service_role' OR public.is_admin());

-- Policies for settings
CREATE POLICY "Settings are viewable by everyone" ON public.settings
  FOR SELECT USING (TRUE);

CREATE POLICY "Settings are manageable by admins" ON public.settings
  FOR ALL USING (auth.role() = 'service_role' OR public.is_admin());

-- Policies for orders
CREATE POLICY "Orders are viewable by admins only" ON public.orders
  FOR SELECT USING (auth.role() = 'service_role' OR public.is_admin());

CREATE POLICY "Orders are insertable by everyone" ON public.orders
  FOR INSERT WITH CHECK (TRUE);

CREATE POLICY "Orders are manageable by admins" ON public.orders
  FOR ALL USING (auth.role() = 'service_role' OR public.is_admin());