-- Create leads table
CREATE TABLE IF NOT EXISTS public.leads (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT,
  company TEXT,
  project_type TEXT,
  budget_range TEXT,
  required_service TEXT,
  project_description TEXT,
  preferred_contact_method TEXT,
  status TEXT DEFAULT 'new' CHECK (status IN ('new', 'contacted', 'qualified', 'in_progress', 'won', 'lost')),
  internal_notes TEXT
);

-- Enable Row Level Security
ALTER TABLE IF EXISTS public.leads ENABLE ROW LEVEL SECURITY;

-- Create policies for leads
CREATE POLICY "Leads are insertable by everyone" ON public.leads
  FOR INSERT WITH CHECK (TRUE);

CREATE POLICY "Leads are manageable by admins" ON public.leads
  FOR ALL USING (auth.role() = 'service_role' OR auth.uid() IN (
    SELECT id FROM auth.users WHERE raw_user_meta_data->>'role' = 'admin'
  ));