-- Create projects table
CREATE TABLE IF NOT EXISTS public.projects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  title TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  client_business TEXT,
  category TEXT,
  technologies JSONB DEFAULT '[]'::jsonb,
  description TEXT,
  problem TEXT,
  solution TEXT,
  screenshots JSONB DEFAULT '[]'::jsonb,
  website_url TEXT,
  app_urls JSONB DEFAULT '[]'::jsonb,
  featured BOOLEAN DEFAULT FALSE NOT NULL,
  completion_date DATE,
  seo_title TEXT,
  seo_description TEXT
);

-- Enable Row Level Security
ALTER TABLE IF EXISTS public.projects ENABLE ROW LEVEL SECURITY;

-- Create policies for projects
CREATE POLICY "Projects are viewable by everyone" ON public.projects
  FOR SELECT USING (TRUE);

CREATE POLICY "Projects are manageable by admins" ON public.projects
  FOR ALL USING (auth.role() = 'service_role' OR auth.uid() IN (
    SELECT id FROM auth.users WHERE raw_user_meta_data->>'role' = 'admin'
  ));