-- Create services table
CREATE TABLE IF NOT EXISTS public.services (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  title TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  short_description TEXT,
  full_content TEXT,
  icon TEXT,
  features JSONB DEFAULT '[]'::jsonb,
  pricing_info JSONB,
  active BOOLEAN DEFAULT TRUE NOT NULL,
  featured BOOLEAN DEFAULT FALSE NOT NULL,
  sort_order INTEGER DEFAULT 0 NOT NULL,
  seo_title TEXT,
  seo_description TEXT
);

-- Enable Row Level Security
ALTER TABLE IF EXISTS public.services ENABLE ROW LEVEL SECURITY;

-- Create policies for services
CREATE POLICY "Services are viewable by everyone" ON public.services
  FOR SELECT USING (active = TRUE);

CREATE POLICY "Services are manageable by admins" ON public.services
  FOR ALL USING (auth.role() = 'service_role' OR auth.uid() IN (
    SELECT id FROM auth.users WHERE raw_user_meta_data->>'role' = 'admin'
  ));