-- Create courses table
CREATE TABLE IF NOT EXISTS public.courses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  title TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  short_description TEXT,
  full_description TEXT,
  instructor TEXT,
  thumbnail TEXT,
  banner TEXT,
  regular_price NUMERIC,
  discounted_price NUMERIC,
  difficulty_level TEXT CHECK (difficulty_level IN ('beginner', 'intermediate', 'advanced')),
  duration TEXT,
  num_lessons INTEGER DEFAULT 0,
  features JSONB DEFAULT '[]'::jsonb,
  requirements JSONB DEFAULT '[]'::jsonb,
  what_youll_learn JSONB DEFAULT '[]'::jsonb,
  featured BOOLEAN DEFAULT FALSE NOT NULL,
  popular BOOLEAN DEFAULT FALSE NOT NULL,
  new_course BOOLEAN DEFAULT FALSE NOT NULL,
  published BOOLEAN DEFAULT FALSE NOT NULL,
  enrollment_status TEXT DEFAULT 'closed' CHECK (enrollment_status IN ('open', 'closed', 'coming_soon')),
  seo_title TEXT,
  seo_description TEXT
);

-- Create course_modules table
CREATE TABLE IF NOT EXISTS public.course_modules (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  course_id BIGINT REFERENCES public.courses(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  description TEXT,
  sort_order INTEGER DEFAULT 0 NOT NULL
);

-- Create course_lessons table
CREATE TABLE IF NOT EXISTS public.course_lessons (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  module_id BIGINT REFERENCES public.course_modules(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  description TEXT,
  video_url TEXT,
  resources JSONB DEFAULT '[]'::jsonb,
  sort_order INTEGER DEFAULT 0 NOT NULL,
  is_preview BOOLEAN DEFAULT FALSE NOT NULL
);

-- Create course_enrollments table
CREATE TABLE IF NOT EXISTS public.course_enrollments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  course_id BIGINT REFERENCES public.courses(id) ON DELETE CASCADE,
  user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  enrollment_date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  status TEXT DEFAULT 'active' CHECK (status IN ('active', 'completed', 'cancelled', 'refunded')),
  payment_amount NUMERIC,
  payment_status TEXT DEFAULT 'pending' CHECK (payment_status IN ('pending', 'paid', 'failed', 'refunded'))
);

-- Enable Row Level Security
ALTER TABLE IF EXISTS public.courses ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.course_modules ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.course_lessons ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.course_enrollments ENABLE ROW LEVEL SECURITY;

-- Create policies for courses
CREATE POLICY "Published courses are viewable by everyone" ON public.courses
  FOR SELECT USING (published = TRUE);

CREATE POLICY "Courses are manageable by admins" ON public.courses
  FOR ALL USING (auth.role() = 'service_role' OR auth.uid() IN (
    SELECT id FROM auth.users WHERE raw_user_meta_data->>'role' = 'admin'
  ));

-- Similar policies for modules and lessons
CREATE POLICY "Modules are viewable by everyone" ON public.course_modules
  FOR SELECT USING (TRUE);

CREATE POLICY "Modules are manageable by admins" ON public.course_modules
  FOR ALL USING (auth.role() = 'service_role' OR auth.uid() IN (
    SELECT id FROM auth.users WHERE raw_user_meta_data->>'role' = 'admin'
  ));

CREATE POLICY "Lessons are viewable by everyone" ON public.course_lessons
  FOR SELECT USING (is_preview = TRUE OR EXISTS (
    SELECT 1 FROM public.course_enrollments ce
    WHERE ce.user_id = auth.uid() AND ce.status = 'active'
    AND ce.course_id = (SELECT course_id FROM public.course_modules WHERE id = course_lessons.module_id)
  ));

CREATE POLICY "Lessons are manageable by admins" ON public.course_lessons
  FOR ALL USING (auth.role() = 'service_role' OR auth.uid() IN (
    SELECT id FROM auth.users WHERE raw_user_meta_data->>'role' = 'admin'
  ));

-- Policies for enrollments
CREATE POLICY "Users can view their own enrollments" ON public.course_enrollments
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own enrollments" ON public.course_enrollments
  FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Enrollments are manageable by admins" ON public.course_enrollments
  FOR ALL USING (auth.role() = 'service_role' OR auth.uid() IN (
    SELECT id FROM auth.users WHERE raw_user_meta_data->>'role' = 'admin'
  ));